ALTER SESSION SET container=FREEPDB1;

GRANT DBA TO test_user;

CREATE TABLE test_user.test_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255),
    dob DATE,
    uuid CHAR(36)
);

CREATE OR REPLACE PROCEDURE TEST_USER.UpdateUserDOB(
  p_user_id IN NUMBER,
  p_dob IN VARCHAR2
) IS
BEGIN
  UPDATE test_user.test_data
  SET dob = p_dob
  WHERE id = p_user_id;

  IF SQL%ROWCOUNT = 0 THEN
    DBMS_OUTPUT.PUT_LINE('No user found with ID ' || p_user_id);
  ELSE
    DBMS_OUTPUT.PUT_LINE('UUID updated for user ID ' || p_user_id);
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE TEST_USER.UpdateUserUUID(
  p_user_id IN NUMBER,
  p_uuid IN CHAR
) IS
BEGIN
  UPDATE test_user.test_data
  SET uuid = p_uuid
  WHERE id = p_user_id;

  IF SQL%ROWCOUNT = 0 THEN
    DBMS_OUTPUT.PUT_LINE('No user found with ID ' || p_user_id);
  ELSE
    DBMS_OUTPUT.PUT_LINE('UUID updated for user ID ' || p_user_id);
  END IF;
END;
/
